#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM

handle_term() {
    echo "I am invincible!!!"
}

trap handle_term SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
